version: '3.1'

services:

  db1:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example1
      PORT: 13306

  db2:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example2
      PORT: 23306
