spring:
  datasource:
      datasource1:
        url: jdbc:mysql://127.0.0.1:13306/database?useSSL=false&requireSSL=false
        username: root
        password: example1
        driverClassName: com.mysql.cj.jdbc.Driver
